# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script:
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script:
    npm install -g appium
  displayName: 'Install Appium'

- script:
    appium --app $APP_PATH &
  displayName: 'Start Appium Server'
  env:
    APP_PATH: $(Build.SourcesDirectory)/apps/ios/UIKitCatalog/UIKitCatalog-iphonesimulator.zip

- bash:
    behave
  displayName: 'Run Automation Testing Scripts'

